# Generated by Django 5.2.6 on 2025-10-07 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_module', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
